---
title: "hwk_explore"
format: html
editor: visual
---

## Libraries & Data

```{r}
library(RColorBrewer)
library(here)
library(tidyverse)

# all hwk data
hwk_data <- read_csv(here("data/hwkdata.csv"))

# data with all flock members in many to one arrangement based on timestamp
hwk_net <- read_csv(here("data/hwk_net.csv"))
view(hwk_net)
```

## Flock Abundance

```{r}
# remove NA
df_filtered <- hwk_net %>% 
  filter(!is.na(flock))

# convert flock to factor
df_filtered$flock <- as_factor(df_filtered$flock)

# calculate abundance and richness
result <- df_filtered %>%
  group_by(timestamp, tar, alarm) %>%
  summarise(richness = n_distinct(flock),
            abundance = n()) %>%
  ungroup()

# join abundance and richeness to trial type
merged_df <- inner_join(result, hwk_data %>% 
                          select(Timestamp_yymmdd_hhmmss, hwk), by = c("timestamp" = "Timestamp_yymmdd_hhmmss"))

# filter out control
df_hwk_filtered <- merged_df %>% 
  filter(hwk != 0)

# Calculate the alarm percentage for each unique richness value
richness_alarm <- df_hwk_filtered %>%
  group_by(richness) %>%
  summarise(alarm_percentage = (sum(alarm) / n()) * 100) %>%
  ungroup()

# Calculate the alarm percentage for each unique abundance value
abundance_alarm <- df_hwk_filtered %>%
  group_by(abundance) %>%
  summarise(alarm_percentage = (sum(alarm) / n()) * 100) %>%
  ungroup()

# Merge richness and abundance alarm percentage dataframes
combined_df <- merge(richness_alarm, abundance_alarm, by = "alarm_percentage", all = TRUE, suffixes = c("_richness", "_abundance"))

# Calculate sample size for richness and abundance
richness_sample_size <- combined_df %>%
  group_by(richness) %>%
  summarise(sample_size = n())

abundance_sample_size <- combined_df %>%
  group_by(abundance) %>%
  summarise(sample_size = n())

# Merge sample sizes with the combined dataframe
combined_df <- left_join(combined_df, richness_sample_size, by = "richness") %>%
  left_join(abundance_sample_size, by = "abundance") %>%
  mutate(sample_size_richness = ifelse(is.na(sample_size.x), 0, sample_size.x),
         sample_size_abundance = ifelse(is.na(sample_size.y), 0, sample_size.y))

# Calculate standard error for alarm percentage
combined_df <- combined_df %>%
  mutate(alarm_percentage_se = sd(alarm_percentage) / sqrt(n()))

# Plot both richness and abundance on the same plot with softer colors
plot_combined <- ggplot(combined_df, aes(x = richness, y = alarm_percentage)) +
  geom_point(aes(color = "Richness"), size = 3) +
  geom_smooth(aes(color = "Richness"), method = "lm", se = FALSE) +
  geom_point(aes(x = abundance, y = alarm_percentage, color = "Abundance"), size = 3) +
  geom_smooth(aes(x = abundance, y = alarm_percentage, color = "Abundance"), method = "lm", se = FALSE) +
  scale_color_manual(values = c("Richness" = "#8c96c6", "Abundance" = "#fc8d59"), name = "Category") + # softer shades of blue and red
  labs(x = "Adundance and Richness", y = "Alarm Percentage") +
  scale_x_continuous(breaks = 1:20) +  # Set x-axis breaks to be in single increments of 1 to 20
  scale_y_continuous(breaks = seq(0, 100, by = 10)) +  # Set y-axis breaks to be in increments of 10 from 0 to 100
  theme_minimal()

# Show the plot
print(plot_combined)

```

## Flock Diversity Plot

work in progress

```{r}
# Function to calculate Shannon's Diversity Index
calculate_shannon_diversity <- function(data) {
  total_count <- sum(data)
  proportions <- data / total_count
  shannon_index <- -sum(proportions * log(proportions))
  return(shannon_index)
}

# Remove NA values from the flock column
df_filtered <- hwk_net %>% 
  filter(!is.na(flock))

# Convert flock column to factor
df_filtered$flock <- as.factor(df_filtered$flock)

# Inner join df_filtered with hwk_data
merged_df <- inner_join(df_filtered, hwk_data %>% 
                          select(Timestamp_yymmdd_hhmmss, hwk), by = c("timestamp" = "Timestamp_yymmdd_hhmmss"))

# Step 1: Filter merged_df to only include rows where hwk equals 1
df_flock <- merged_df %>%
  filter(hwk == 1)

# Step 2: Calculate Shannon Diversity Index for each timestamp
df_hwk_diversity <- df_flock %>%
  group_by(timestamp) %>%
  summarise(shannon_diversity = {
    if (length(unique(flock)) > 1) {
      # Calculate Shannon Diversity Index for each unique flock value
      shannon_indices <- sapply(unique(flock), function(f) calculate_shannon_diversity(table(flock[flock == f])))
      # Average Shannon Diversity Index
      mean(shannon_indices, na.rm = TRUE)
    } else if (length(unique(flock)) == 1) {
      # If there is only one unique flock value, set diversity to 0
      calculate_shannon_diversity(table(flock))
    } else {
      # If there are no flock values, set diversity to NaN
      NaN
    }
  },
  alarm = first(alarm)) %>%
  ungroup()


# Step 3: Calculate alarm percentage based on unique Shannon Index values
alarm_percentage <- df_hwk_diversity %>%
  group_by(shannon_diversity) %>%
  summarise(alarm_percentage = mean(alarm)) %>%
  ungroup()

# Step 4: Plot alarm percentage on the y-axis and diversity on the x-axis
plot_combined <- ggplot(alarm_percentage, aes(x = shannon_diversity, y = alarm_percentage)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Shannon Diversity Index", y = "Alarm Percentage") +
  scale_x_continuous(breaks = seq(0, 4, by = 0.5)) +  # Set x-axis breaks
  scale_y_continuous(breaks = seq(0, 1, by = 0.1)) +  # Set y-axis breaks
  theme_minimal()

# Show the plot
print(plot_combined)

```

## Debugging Diversity

```{r}
# Print out unique values of flock for each timestamp
for (i in 1:nrow(df_hwk_diversity)) {
  timestamp <- df_hwk_diversity$timestamp[i]
  flock_values <- df_flock[df_flock$timestamp == timestamp, "flock"]
  unique_flock <- unique(flock_values)
  cat("Timestamp:", timestamp, "\n")
  cat("Unique Flock Values:", paste(unique_flock, collapse = ", "), "\n\n")
}

```

## Abundance and Richness by Target Species

```{r}
# Remove NA values from the flock column
df_filtered <- hwk_net %>% 
  filter(!is.na(flock))

# Convert flock column to factor
df_filtered$flock <- as.factor(df_filtered$flock)

# Inner join df_filtered with hwk_data
merged_df <- inner_join(df_filtered, hwk_data %>% 
                          select(Timestamp_yymmdd_hhmmss, hwk), by = c("timestamp" = "Timestamp_yymmdd_hhmmss"))
# Step 1: Filter merged_df to only include rows where hwk equals 1
df_flock <- merged_df %>%
  filter(hwk == 1)

df_flock <- df_flock %>% 
  filter(!is.na(flock))

# Step 1: Group by timestamp and tar, then calculate richness and abundance
result <- df_filtered %>%
  group_by(timestamp, tar, alarm) %>%
  summarise(richness = n_distinct(flock),
            abundance = n()) %>%
  ungroup()

# Step 1: Calculate alarm percentage for each unique richness value for each species
alarm_percentage_richness <- result %>%
  group_by(tar, richness) %>%
  summarise(alarm_percentage = mean(alarm)) %>%
  ungroup()

# Step 2: Calculate alarm percentage for each unique abundance value for each species
alarm_percentage_abundance <- result %>%
  group_by(tar, abundance) %>%
  summarise(alarm_percentage = mean(alarm)) %>%
  ungroup()

# Step 3: Combine the results into a single dataframe
combined_df <- full_join(alarm_percentage_richness, alarm_percentage_abundance, by = "tar")

# Show the combined dataframe
print(combined_df)

# Combine alarm percentage data for richness and abundance
combined_data <- bind_rows(
  mutate(alarm_percentage_richness, variable = "Richness"),
  mutate(alarm_percentage_abundance, variable = "Abundance")
)

# Combine richness and abundance into a single variable
combined_data <- combined_data %>%
  mutate(richness_abundance = ifelse(variable == "Richness", richness, abundance))

# Group the data by tar and check if all alarm percentages are zero
filtered_data <- combined_data %>%
  group_by(tar) %>%
  filter(!all(alarm_percentage == 0)) %>%
  ungroup()

# Define a color palette with 10 distinct colors
color_palette <- c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00", "#ffff33", "#a65628", "#f781bf", "#999999", "#000000")


# Define colors for richness and abundance
richness_color <- "blue"
abundance_color <- "red"

# Plot regressions based on Alarm Percentage on y and richness/abundance on the x, faceted by tar
plot <- ggplot(filtered_data, aes(x = richness, y = alarm_percentage)) +
  geom_point(data = filtered_data[filtered_data$variable == "Richness",], aes(color = "Richness", shape = "Richness"), size = 3) + # Increase size for richness points
  geom_smooth(data = filtered_data[filtered_data$variable == "Richness",], aes(x = richness, color = "Richness"), method = "lm", se = FALSE, linetype = "dashed") +
  geom_point(data = filtered_data[filtered_data$variable == "Abundance",], aes(x = abundance, y = alarm_percentage, color = "Abundance", shape = "Abundance")) +
  geom_smooth(data = filtered_data[filtered_data$variable == "Abundance",], aes(x = abundance, y = alarm_percentage, color = "Abundance"), method = "lm", se = FALSE, linetype = "dotted") +
  labs(x = "Richness and Abundance", y = "Alarm Percentage", color = "Variable") +
  scale_color_manual(values = c(Richness = richness_color, Abundance = abundance_color), 
                     labels = c(Richness = "Richness", Abundance = "Abundance")) +
  scale_shape_manual(values = c(Richness = 15, Abundance = 16), 
                     labels = c(Richness = "Richness", Abundance = "Abundance")) +
  theme_minimal() +
  facet_wrap(~ tar, scales = "free") +
  theme(legend.text = element_text(face = "bold"),
        strip.text = element_text(face = "bold"))  # Make strip text bold

# Print the plot
print(plot)

```
